BUTTONS = []

COLOR_RED = "#ff0000"
COLOR_BLACK = "#000000"
COLOR_BLUE_DARK = "#669999"
COLOR_BLUE_SKY = "#33ccff"

COLOR_ENABLED = COLOR_BLACK
COLOR_DISABLED = COLOR_RED

MODE_FREE = 0
MODE_GUESS_NOTE = 1

MODE = MODE_GUESS_NOTE
BUTTON_MODE = None